#!/bin/bash



timestamp=$(date +"%m-%d-%h-%m")

echo $timestamp

sudo cp -rf $1 /Users/OSX/git/junilyd.github.io/dump/$timestamp_$1 && 

cd /Users/OSX/git/junilyd.github.io/dump && 

git add -A && git commit -a -m "Auto Commit" && 

git push -u origin master 

echo "https://github.com/junilyd/junilyd.github.io/tree/master/dump/$timestamp_$1"
